services:
  db:
      image: mysql:latest
      restart: always
      ports: 
        - "3306:3306"
      volumes: 
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - db:/var/lib/mysql
      environment: 
        MYSQL_ROOT_PASSWORD: password
  
volumes: 
  db:
      
